NewAuction/Models/Ban.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewAuction.Models
{
    public class Ban
    {
        public virtual ApplicationUser User { get; set; }
    }
}

NewAuction/Controllers/BanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewAuction.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace NewAuction.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class BanController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationDbContext db = new ApplicationDbContext();
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? new ApplicationUserManager(new UserStore<ApplicationUser>(db));
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index(string sortOrder, int id = -1)
        {
            IQueryable<ApplicationUser> students = null;
            var products = from s in db.Product where s.Buyer != null select s;
            ViewBag.Auctions = products;
            ViewBag.productId = id;
            ViewBag.DateSortParam = sortOrder == "Address" ? "address_desc" : "Address";
            if (id == -1)
            {
                students = from s in db.Users select s;
            }
            else
            { 

                var auction = products.Where(x => x.ID == id).First();
                var usersInAuction = from s in db.Bet where s.Product.ID == auction.ID select s.User;


                students = from s in db.Users
                               where usersInAuction.Contains(s)
                               select s;
            }

            switch (sortOrder)
            {
                case "Address":
                    students = students.OrderBy(s => s.Address);
                    break;
                case "address_desc":
                    students = students.OrderByDescending(s => s.Address);
                    break;
                default:
                    students = students.OrderBy(s => s.Email);
                    break;
            }
            return View(students.ToList());
        }

        public ActionResult BanUser(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            if (user.IsBanned == true)
                return RedirectToAction("Index");

            user.IsBanned = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Disban(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            if (user.IsBanned == false)
                return RedirectToAction("Index");

            user.IsBanned = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewAuction/Views/Ban/Index.cshtml
@model IEnumerable<NewAuction.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    var redirectURL = Url.Action("Index","Ban");

    var sort = @ViewBag.DateSortParam;
    string src = "";
    if (sort == "" || sort == null)
       src = redirectURL + "?id=" + @ViewBag.productId;
    else
        src = redirectURL + "?id=" + @ViewBag.productId + "&sortOrder=" + sort;
}

<h2>Users</h2>

<select id="dropdown">
    @foreach (var i in ViewBag.Auctions)
    {
        if (ViewBag.productId == i.ID)
        {
            <option value="@i.ID" selected>@i.Name (@i.User.UserName)</option>
        }
        else
        {
            <option value="@i.ID">@i.Name (@i.User.UserName)</option>
        }
    }
</select>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            <a href="@src" id="address">Address</a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsBanned)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsBanned)
        </td>

        <td>
            @Html.ActionLink("Ban", "BanUser", new { id = item.Id })
        </td>
        <td>
            @Html.ActionLink("Disban", "Disban", new { id = item.Id })
        </td>


    </tr>
    }

</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    
    $(function () {
        $("#dropdown").change(function () {
            var selectedItem = $("#dropdown option:selected").val();
            var redirectURL = '@Url.Action("Index","Ban")';
            window.location.href = redirectURL + "?id=" + selectedItem;
        });
    })
</script>